version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keycloak-network
  keycloak:
    build: ./keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      DB_ADDR: postgres
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    networks:
      - keycloak-network
  client:
    image: hexdump95/client:latest
    build: ./client
    container_name: client
    ports:
      - "80:80"
    networks:
      - keycloak-network
  api:
    image: hexdump95/api:0.0.1-SNAPSHOT
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    networks:
      - keycloak-network
networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge
volumes:
  postgres-data:
    name: postgres-data
